apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: team-alpha
rules:
- apiGroups: {"", "apps"}
  resources: {"pods", "deployments", "services", "configmaps"}
  verbs: {"get", "list", "watch", "create", "update", "patch"}
- apiGroups: {""}
  resources: {"pods/log"}
  verbs: {"get", "list"}
