pipeline {
    agent any
    
    tools {
        maven 'Maven-3.9'
    }
    
    parameters {
        choice(
            name: 'ENVIRONMENT',
            choices: ['dev', 'staging', 'production'],
            description: 'Select which enviornment to deploy to'
        )
    }

    environment {
        APP_NAME = 'java-app'
        DOCKERHUB_USERNAME = 'sri24devops'
        DOCKERHUB_REPO = "${DOCKERHUB_USERNAME}/${APP_NAME}"
        APP_PORT = "${params.ENVIRONMENT == 'production' ? '8081' : params.ENVIRONMENT == 'staging' ? '8083' : '8082'}"
    }
    
    stages {
        stage('Show Build Parameters') {
            steps {
                echo "=========================================="
                echo "Selected Environment: ${params.ENVIRONMENT}"
                echo "=========================================="
            }
        }

        stage('Build JAR with Maven') {
            steps {
                echo "Building JAR file with Maven"
                dir('Day-5/java-cicd') {
                    sh '''
                      mvn --version
                      mvn clean package
                      ls -lh target/
                    '''
                }
            }
        }
        
        stage('Build and Scan in parallel') {
            parallel {
                stage('Build Docker Image') {
                    steps {
                        echo "Using Eclipse Temurin (OpenJDK replacement)"
                        dir('Day-5/java-cicd') {
                            sh '''
                                docker build -t ${APP_NAME}:${BUILD_NUMBER} .
                                docker tag ${APP_NAME}:${BUILD_NUMBER} ${DOCKERHUB_REPO}:${BUILD_NUMBER}
                                docker tag ${APP_NAME}:${BUILD_NUMBER} ${DOCKERHUB_REPO}:latest
                                docker images | grep ${APP_NAME}

                                echo "Image size:"
                                docker images ${APP_NAME}:${BUILD_NUMBER} --format "{{.Size}}"
                            '''
                        }
                    }
                }

                stage('Run Unit Tests') {
                    steps {
                        echo "🧪 Running unit tests..."
                        dir('Day-5/java-cicd') {
                            sh '''
                                echo "Running Maven tests for verification..."
                                mvn test
                                echo "Test results:"
                                cat target/surefire-reports/*.txt 2>/dev/null || echo "No test reports"
                                echo "✅ Unit tests passed!"
                            '''
                        }
                    }
                }
                
                stage('Code Quality Check') {
                    steps {
                        echo "📊 Running code quality checks..."
                        dir('Day-5/java-cicd') {
                            sh '''
                                echo "Checking code style..."
                                # Simple line count check
                                find src -name "*.java" | wc -l
                                echo "✅ Code quality check passed!"
                            '''
                        }
                    }
                }
            }
        }

        stage('Trivy Security Scan') {
            steps {
                echo "Running Trivy image security scan"
                sh '''
                    # Use cached Trivy or install
                    if [ ! -f /var/jenkins_home/tools/trivy ]; then
                        echo "Installing Trivy (one-time setup)..."
                        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /var/jenkins_home/tools
                    fi
                    
                    export PATH=\$PATH:/var/jenkins_home/tools

                    echo "Trivy version:"
                    trivy --version

                    echo "Scanning ${APP_NAME}:${BUILD_NUMBER} for CRITICAL vulnerabilities..."
                    trivy image \
                        --exit-code 1 \
                        --severity CRITICAL \
                        --no-progress \
                        ${APP_NAME}:${BUILD_NUMBER}

                    echo "Scan complete. No CRITICAL vulnerabilities found!"
                '''
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                echo "Pushing to DockerHub"
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'dockerhub_cred',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )]) {
                        sh '''
                            echo "Logging in to DockerHub"
                            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

                            echo "Pushing ${DOCKERHUB_REPO}:${BUILD_NUMBER}"
                            docker push ${DOCKERHUB_REPO}:${BUILD_NUMBER}

                            echo "Pushing ${DOCKERHUB_REPO}:latest"
                            docker push ${DOCKERHUB_REPO}:latest

                            docker logout
                            echo "Image pushed to DockerHub successfully"
                            
                        '''
                        }
                 }
            }
        }
 
        stage('Approval to Deploy') {
            steps {
                timeout(time: 30, unit: 'MINUTES') {
                    input message: 'Image scanned and pushed. Deploy container?',
                          ok: 'Yes, Deploy Now'
                }
            }
        }
                

        stage('Cleanup Old Containers') {
            steps {
                echo "Cleaning up old containers ..."
                sh """
                # Stop and remove old containers (without environment suffix)
                docker stop ${APP_NAME} 2>/dev/null || true
                docker rm ${APP_NAME} 2>/dev/null || true

                # Stop and remove old containers (with environment suffix)
                docker stop ${APP_NAME}-${params.ENVIRONMENT} 2>/dev/null || true
                docker rm ${APP_NAME}-${params.ENVIRONMENT} 2>/dev/null || true
                echo "Cleanup complete"
                """
            }
        }

        stage('Deploy container') {
            steps {
                echo "Deploying to ${params.ENVIRONMENT} from DockerHub"
                sh """
                    # Stop old container (if exists)
                    # 2>/dev/null: Suppress error messages
                    # || true: Don't fail if container doesn't exist
                    docker stop ${APP_NAME}-${params.ENVIRONMENT} 2>/dev/null || true
                    docker rm ${APP_NAME}-${params.ENVIRONMENT} 2>/dev/null || true

                    echo "Pulling from DockerHub"
                    docker pull ${DOCKERHUB_REPO}:${BUILD_NUMBER}

                    echo "Starting new container"
                    docker run -d -p ${APP_PORT}:8080 --name ${APP_NAME}-${params.ENVIRONMENT} --restart unless-stopped ${DOCKERHUB_REPO}:${BUILD_NUMBER}

                    # Wait for Spring Boot to start
                    sleep 30
                    
                    docker ps | grep ${APP_NAME}-${params.ENVIRONMENT}
                    echo "Container is running on port ${APP_PORT}!"
                    echo "${params.ENVIRONMENT} deployment is successful!"
                """
            }
        }

        stage('Test Application') {
            steps {
                echo "Testing Application in ${params.ENVIRONMENT}"
                sh """
                    echo "Test1: Home page"
                    docker exec ${APP_NAME}-${params.ENVIRONMENT} curl -f http://localhost:8080

                    echo "Test2: Hello endpoint"
                    docker exec ${APP_NAME}-${params.ENVIRONMENT} curl -f http://localhost:8080/api/hello

                    echo "Test3: Health endpoint"
                    docker exec ${APP_NAME}-${params.ENVIRONMENT} curl -f http://localhost:8080/wrong-endpoint

                    echo "All Tests passed!"
                """
            }
        }
    }

    post {
        success {
            echo '========================================'
            echo 'PIPELINE SUCCESS WITH DOCKER HUB!'
            echo '========================================'
            echo "Docker Hub: https://hub.docker.com/r/${DOCKERHUB_REPO}"
            echo "Pull Command: docker pull ${DOCKERHUB_REPO}:${BUILD_NUMBER}"
            echo "Application url: http://192.168.1.9:${APP_PORT}"
            echo "Tags: ${BUILD_NUMBER}, latest"
            echo "Image: eclipse-temurin:17-jdk"
            echo "docker pull ${DOCKERHUB_REPO}:latest"
            echo "docker run -p 8080:8080 ${DOCKERHUB_REPO}:latest"
            echo "========================================"
        }

        failure {
            echo '========================================='
            echo 'PIPELINE FAILED'
            echo '========================================='
            script {
                def previousBuild = env.BUILD_NUMBER.toInteger() - 1
                
                if (previousBuild < 1) {
                    echo "Build #1 failed. No previous version to rollback to."
                } else {
                    sh """
                        echo "Gathering failure information..."
                        echo ""
                        echo "=== Container Status ==="
                        docker ps -a | grep ${APP_NAME} || echo "No container found"
                        echo ""
                        echo "=== Container Logs ==="
                        docker logs ${APP_NAME}-${params.ENVIRONMENT} 2>&1 \
                        || echo "No logs available"
                        echo ""
                        echo "=== Docker Images ==="
                        docker images | grep ${APP_NAME} || echo "No images"
                        echo ""
                        echo "=== Starting Rollback to Build ${previousBuild} ==="

                        docker stop ${APP_NAME}-${params.ENVIRONMENT} \
                        2>/dev/null || true
                        docker rm ${APP_NAME}-${params.ENVIRONMENT} \
                        2>/dev/null || true

                        if docker pull ${DOCKERHUB_REPO}:${previousBuild}; then
                            docker run -d \\
                                -p ${APP_PORT}:8080 \\
                                --name ${APP_NAME}-${params.ENVIRONMENT} \\
                                --restart unless-stopped \\
                                ${DOCKERHUB_REPO}:${previousBuild}

                            echo "✅ Rollback successful to build ${previousBuild}"
                        else
                            echo "❌ Image ${DOCKERHUB_REPO}:${previousBuild} not found"
                            echo "Manual intervention required"
                        fi
                    """
                }
            }
            echo '=========================================='
        }

        always {
            sh 'docker image prune -f || true'
        }
    }
}
