pipeline {
    agent any
    
    tools {
        maven 'Maven-3.9'
    }
    
    environment {
        APP_NAME = 'java-app'
    }
    
    stages {
        stage('Build JAR with Maven') {
            steps {
                echo "Building JAR file with Maven"
                dir('Day-5/java-cicd') {
                    sh '''
                      mvn --version
                      mvn clean package
                      ls -lh target/
                    '''
                }
            }
        }
    }
}