pipeline {
    agent any
    
    tools {
        maven 'Maven-3.9'
    }
    
    environment {
        APP_NAME = 'java-app'
    }
    
    stages {
        stage('Build JAR with Maven') {
            steps {
                echo "Building JAR file with Maven"
                dir('Day-5/java-cicd') {
                    sh '''
                      mvn --version
                      mvn clean package
                      ls -lh target/
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Using Eclipse Temurin (OpenJDK replacement)"
                dir('Day-5/java-cicd') {
                    sh '''
                        docker build -t ${APP_NAME}:${BUILD_NUMBER} .
                        docker images | grep ${APP_NAME}

                        echo "Image size:"
                        docker images ${APP_NAME}:${BUILD_NUMBER} --format "{{.Size}}"
                    '''
                }
            }
        }

        stage('Deploy container') {
            steps {
                echo "Deploying container"
                sh '''
                    # Stop old container (if exists)
                    # 2>/dev/null: Suppress error messages
                    # || true: Don't fail if container doesn't exist
                    docker stop ${APP_NAME} 2>/dev/null || true
                    docker rm ${APP_NAME} 2>/dev/null || true

                    docker run -d -p 8081:8080 --name ${APP_NAME} ${APP_NAME}:${BUILD_NUMBER}
                    
                    docker ps | grep ${APP_NAME}
                    echo "Container is running!"
                '''
            }
        }

        stage('Test Application') {
            steps {
                echo "Testing Application"
                sh '''
                    echo "Test1: Home page"
                    docker exec ${APP_NAME} curl -f http://localhost:8080
                '''
            }
        }
    }
}